spring:
  application:
    name: ms.travel.application
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    url: jdbc:postgresql://172.26.16.128:5444/guarantee_online?currentSchema=public
    username: guarantee_online_acc
    password: guarantee_online_acc_2023
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: liquibase/changelog-master.yml
  jpa:
    show-sql: true

server:
  port: 8082

token:
  key: SRrdxDWe8NGM-/0uQrB!RHLtT2cbczHeT633kq2E3mXn2XrJSx69Y1JNjITNiVt1

url:
  base:
    soft-10: https://wp.soft10.az
